Cards docs
labcodes/labstorybook pull request #100
Opened 2021-01-19 19:37 UTC by rhannandrade

**Link to task**
https://labcodes.atlassian.net/browse/DSYS-196

**How to test**
With the labsystem running, go to the Card tab and check if everything is according to the documentation.
See https://www.figma.com/file/Wx7jj5klQn3YsRA2XcIV3E/%F0%9F%93%9A-Components?node-id=8904%3A70931 for a detailed reference.

**Description**
This PR translates Card's documentation from Figma to Storybook.
Also changes the` .doc-anatomy-block` color to fix accessibility issues on Card's story and on all the other components stories.

2021-01-19 21:11 UTC, falconedani requested changes
Great translation from Figma to the template. I've just pointed small fixes to the text.

Other fixes:
* Update the images for sizes and responsiveness. They are displaying different ranges on the descriptions and inside the card representation (white rectangle).
* Update Styles images removing the header icon.

2021-01-19 21:11 UTC, falconedani commented on stories/Card.stories.mdx
> +    <h2>Styles & color combination</h2>
```suggestion
    <h2>Styles</h2>
```

2021-01-19 21:11 UTC, falconedani commented on stories/Card.stories.mdx
> +        <img src="docs/card/desktop.png" alt="Cards responsivess for desktop"/>
```suggestion
        <img src="docs/card/desktop.png" alt="Card responsive size and placement example for desktop. Min of 2 columns and max of 6."/>
```

2021-01-19 21:11 UTC, falconedani commented on stories/Card.stories.mdx
> +        <img src="docs/card/tablet.png" alt="Cards responsivess for tablet"/>
```suggestion
        <img src="docs/card/tablet.png" alt="Card responsive size and placement examples for tablet. Min 4 columns, max 12 columns."/>
```

2021-01-19 21:11 UTC, falconedani commented on stories/Card.stories.mdx
> +        <img src="docs/card/mobile.png" alt="Cards responsivess for mobile"/>
```suggestion
        <img src="docs/card/mobile.png" alt="Card responsive size and placement example for mobile. Min 6 columns, max 12 columns."/>
```

2021-01-19 21:11 UTC, falconedani commented on stories/Card.stories.mdx
> +        <div className="doc-em-block">
```suggestion
        <br />
        <div className="doc-em-block">
```

Added it because it looks too close to the image.

2021-01-20 14:27 UTC, rhannandrade commented on .storybook/scss/doc-utils.scss
> +  box-shadow: $mineral-20 0 1px 3px 0;
After we talk, I decide to keep this to match Storybook's canvas border style.

2021-01-20 17:55 UTC, falconedani approved these changes
LGTM

2021-01-20 17:55 UTC, merged