DSYS6/buttons-js
labcodes/labstorybook pull request #33
Opened 2020-08-21 18:15 UTC by CavalcanteLucas

**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-6

**How to test:**
- With the _LabSystem_ running, go to the `Component/Button` div in the _LabStoryBook_, then check if all components are rendered as expected.
- Locally, from `labstorybook` dir, run `npm run test -- -u`, then check if all tests are passing.

**Description of your solution:**
This PR refactor the architecture of `Button` and introduces `AbstractButton`. The later should serve as a "private" component, to be used for building "public" `[Default]Button`, `TextButton` and `OutlineButton` components through the `variant` props. Support for passing click-handlers as props to `Button`-related components are also enabled. `Button.stories` is refactored accordingly, with minor syntax fixes. Some snapshot-based tests are implemented as well.

2020-08-25 18:07 UTC, lucianoratamero commented on labsystem/src/Button/AbstractButton.js
>      icon: undefined,
Since the default for the skin is undefined, this happens if you don't pass it: 
![image](https://user-images.githubusercontent.com/1103672/91210996-6e8eb680-e6e4-11ea-881a-f3d7341dbe4f.png)

To solve this `btn--undefined` class, we have two options:
- make the skin required;
- or check if a skin was passed when adding the class to the button (line 63).

We'll probably go with the second approach, right, @debscorreia ?

2020-08-25 18:11 UTC, lucianoratamero commented on labsystem/src/Button/AbstractButton.js
> +    handleClick: PropTypes.func,
Instead of `handleClick`, we should use `onClick`, since it's what the user expects the prop to be named when adding onclick events handlers.

2020-08-25 18:13 UTC, lucianoratamero commented on labsystem/src/Button/AbstractButton.test.js
> +  });
I think you're missing some tests here:

- rendering with an icon;
- padding the click event to the `onClick` prop.

2020-08-25 18:14 UTC, lucianoratamero commented on labsystem/src/Button/Button.test.js
> +});
Same thing about the missing tests here.

2020-08-25 18:14 UTC, lucianoratamero commented on labsystem/src/Button/OutlineButton.test.js
> +});
And here

2020-08-25 18:14 UTC, lucianoratamero commented on labsystem/src/Button/TextButton.test.js
> +});
And here

2020-08-25 18:16 UTC, lucianoratamero commented on stories/Buttons.stories.mdx
>  <Meta title="Components/Button" component={Button} />
The title for the sidebar is "Button", while the docs title is "Buttons" (line 12).
They should be consistent, and since we have mutiple buttons, I guess we should go with "Buttons" for everything.

2020-08-25 22:22 UTC, olgapinheiro commented on labsystem/src/Button/AbstractButton.js
>          disabled={disabled}
Maybe it would be better to only pass disabled if it is false, as we did in the AbstractTextButton component, to avoid getting a component that is not disabled when querying for a disabled component.
e.g.: $(button[disabled])

2020-08-25 22:27 UTC, olgapinheiro commented on labsystem/src/Button/Button.test.js
> +});
The `renders as expected when passing disabled as true` could also test if the disabled param is passed to the button tag itself

2020-08-26 18:48 UTC, CavalcanteLucas commented on labsystem/src/Button/AbstractButton.js
>      icon: undefined,
In the case of the second approach, what would be the answer in case skin was **not** passed?

2020-08-26 18:51 UTC, CavalcanteLucas commented on labsystem/src/Button/AbstractButton.js
> +    handleClick: PropTypes.func,
Thank you, fixed.

2020-08-26 20:35 UTC, CavalcanteLucas commented on labsystem/src/Button/AbstractButton.test.js
> +  });
Thank you, fixed.

2020-08-26 20:35 UTC, CavalcanteLucas commented on labsystem/src/Button/OutlineButton.test.js
> +});
Thank you, fixed.

2020-08-26 20:35 UTC, CavalcanteLucas commented on labsystem/src/Button/TextButton.test.js
> +});
Thank you, fixed.

2020-08-26 20:47 UTC, CavalcanteLucas commented on labsystem/src/Button/Button.test.js
> +});
Thank you @lucianoratamero , fixed.

You mean like [here](https://github.com/labcodes/labstorybook/blob/inputs/labsystem/src/Input/AbstractTextInput.test.js#L24) @olgapinheiro ?

2020-08-26 22:05 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
>  <Meta title="Components/Button" component={Button} />
Thank you, fixed.

2020-08-26 22:08 UTC, CavalcanteLucas commented on labsystem/src/Button/AbstractButton.js
>          disabled={disabled}
You mean like what you did in `AbstractTextInput` in [here](https://github.com/labcodes/labstorybook/blob/inputs/labsystem/src/Input/AbstractTextInput.js#L185)?

2020-08-27 15:02 UTC, debscorreia commented on labsystem/src/Button/AbstractButton.js
>      icon: undefined,
Hey @lucianoratamero @CavalcanteLucas Yes, I agree we should go with the second approach. If the skin is not passed we don't need to add any class, I believe.

2020-08-28 17:35 UTC, CavalcanteLucas commented on labsystem/src/Button/AbstractButton.js
>      icon: undefined,
Ok, fixed.

2020-08-31 18:06 UTC, lucianoratamero commented on labsystem/src/Buttons/AbstractButton.js
> +    const classNameSkin = `${skin ? ` btn--${skin} ` : " "}`;
I'm not sure I like this decision to solve the issue.
I think I'd prefer something similar to what Dani and Debs have done in the tags PR: https://github.com/labcodes/labstorybook/pull/34/files#diff-01285b0886dd8bd04db71b49abfd6aebR131

2020-08-31 18:11 UTC, lucianoratamero commented on stories/Buttons.stories.mdx
> +<p>Primary calls to action on a dialog or on a page should be represented by a default (filled) button. Secondary or related actions should be represented by a ghost (outlined) button. A text button
could you change all the mentions of a "ghost" button to an "outlined" one

2020-08-31 18:19 UTC, lucianoratamero commented on stories/Buttons.stories.mdx
> +import TextButton from '../labsystem/src/Buttons/TextButton';
quick thing: could you change the imports so that every button is imported from '../labsystem/src/Buttons' ?

2020-09-01 17:08 UTC, CavalcanteLucas commented on labsystem/src/Buttons/AbstractButton.js
> +    const classNameSkin = `${skin ? ` btn--${skin} ` : " "}`;
ok, fixed.

2020-09-01 17:10 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
> +<p>Primary calls to action on a dialog or on a page should be represented by a default (filled) button. Secondary or related actions should be represented by a ghost (outlined) button. A text button
ok, fixed.

2020-09-01 17:29 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
> +import TextButton from '../labsystem/src/Buttons/TextButton';
sure, fixed.

2020-09-02 18:22 UTC, lucianoratamero commented on labsystem/src/Buttons/Button.js
> +    return <AbstractButton variant="default" {...this.props} />;
instead of prop spreading,  we should explicitly pass each prop to the AbstractButton component.

2020-09-02 18:22 UTC, lucianoratamero commented on labsystem/src/Buttons/OutlineButton.js
> +    return <AbstractButton variant="outline" {...this.props} />;
instead of prop spreading,  we should explicitly pass each prop to the AbstractButton component.

2020-09-02 18:22 UTC, lucianoratamero commented on labsystem/src/Buttons/TextButton.js
> +    return <AbstractButton variant="text" {...this.props} />;
instead of prop spreading,  we should explicitly pass each prop to the AbstractButton component.

2020-09-02 19:41 UTC, CavalcanteLucas commented on labsystem/src/Buttons/Button.js
> +    return <AbstractButton variant="default" {...this.props} />;
fixed.

2020-09-02 19:41 UTC, CavalcanteLucas commented on labsystem/src/Buttons/OutlineButton.js
> +    return <AbstractButton variant="outline" {...this.props} />;
fixed.

2020-09-02 19:41 UTC, CavalcanteLucas commented on labsystem/src/Buttons/TextButton.js
> +    return <AbstractButton variant="text" {...this.props} />;
fixed.

2020-09-10 18:41 UTC, lucianoratamero requested changes

2020-09-10 18:41 UTC, lucianoratamero commented on labsystem/scss/components/_lab-button.scss
> +  width: 100%;
I think you'll need to add `display: block` here as well, for some corner cases.

2020-09-11 20:45 UTC, debscorreia commented on labsystem/scss/components/_lab-button.scss
> +  width: 100%;
@lucianoratamero I tested here and actually there's no need. the `.btn` class already has `display: inline-flex`. When applying the 100% width it will take the entire parent's width and keep the flex behavior to align itens internally.

I think this is good to go!

cc @CavalcanteLucas

2020-09-11 21:14 UTC, lucianoratamero commented on labsystem/scss/components/_lab-button.scss
> +  width: 100%;
ty for the review @debscorreia !

2020-09-11 21:14 UTC, lucianoratamero approved these changes

2020-09-12 02:08 UTC, debscorreia approved these changes

2020-09-14 20:15 UTC, merged