DSYS-22/tags-js
labcodes/labstorybook pull request #35
Opened 2020-09-11 21:47 UTC by CavalcanteLucas

**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-22

**How to test:**
- With the LabSystem running, go to the Component/Button div in the LabStoryBook, then check if all components are rendered as expected.
- Locally, from labstorybook dir, run `npm run test -- -u`, then check if _all_ tests are passing.

**Description of your solution:**
This PR refactor the architecture of `Tags`.  It introduces `AbstractTag` and old `Tag` is now deprecated. `AbstractTag` serve as a "private" component, to be used for building "public"  components of type: `SimpleTag`, `RemovableTag`, `TogglableTag` or `DropdownTag`. `Tag.stories` is refactored accordingly, also including a `TagPlayground`. Tests are implemented in this PR as well.

2020-09-24 15:23 UTC, lucianoratamero requested changes

2020-09-24 15:23 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.js
> +    onClick: PropTypes.func,
as we discussed before, our current convention is that all stateful props that are not html attributes need to be prefixed with `is`, like `isTogglable`, for example.
in this case, only `disabled` is an html attribute, so `togglable`, `dropdown`, `removable`, `outline` and `selected` need to have an `is` before it and be camel-cased.

2020-09-24 15:23 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.js
> +    selected: PropTypes.bool,
as we discussed before, `selected` is only used on `TogglableTag`s, and the proper way to call it is if it's on or off.
so we need to change `selected` to `on`. together with my other comment, it should be `isOn`, since we need to prefix it with `is`.

2020-09-24 15:23 UTC, lucianoratamero commented on labsystem/src/Tags/DropdownTag.test.js
> +    expect(mountedComponent.find("Tag").prop("disabled")).toEqual(true);
since we changed the way to test our components, instead of testing by finding the internal react component and checking their props, we should test that, if we pass `disabled`, the disabled class is added to the rendered html.

same thing for the other props (outline and color) and for the other components' tests.

2020-09-24 15:23 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.js
>    selected = () => {
I'm pretty sure this method is exclusively used on the `TogglableTag`, so it should be implemented on it.
the same could be said for the `Dropdown` and `Removable` tags.

2020-09-24 15:23 UTC, lucianoratamero commented on labsystem/src/Tags/DropdownTag.test.js
> +import React from "react";
we're not testing two things here:
- that the dropdown tag has the dropdown class;
- that the dropdown tag is rendering the icon.

so we need to add test for those.

same comment applies for the other tags.

2020-09-24 15:23 UTC, lucianoratamero commented on labsystem/src/Tags/RemovableTag.test.js
> +    "https://avatars3.githubusercontent.com/u/1887591?s=400&u=ba45b6433752099210bf180b4448fb82e015c3a8&v=4";
we shouldn't use external resources in our tests. 

I haven't tried it, but it may be the case that this test is really making the request for the thumb.

so just fake it, since the image doesn't really matter and any string will do. same comment applies for other tests that use it.

2020-09-24 15:36 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
>  export default class Tag extends React.Component {
indeed, thank you. fixed

2020-09-24 16:58 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    onClick: PropTypes.func,
ok, fixed

2020-09-24 17:18 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    selected: PropTypes.bool,
ok, fixed.

2020-09-24 17:29 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
>    selected = () => {
Actually, it seems that the `icon` method can be used by `SimpleTag`, `DropdownTag` and `RemovableTag`.

I agree about the `dropdownIcon` and `removeIcon` methods, but there is no access to the `<span>` that contains the `text` from `DropdownTag` and `RemovableTag` classes.

2020-09-24 19:36 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.test.js
> +    expect(mountedComponent.find("Tag").prop("disabled")).toEqual(true);
ok, fixed.

2020-09-24 21:31 UTC, CavalcanteLucas commented on labsystem/src/Tags/RemovableTag.test.js
> +    "https://avatars3.githubusercontent.com/u/1887591?s=400&u=ba45b6433752099210bf180b4448fb82e015c3a8&v=4";
ok, fixed.

2020-09-25 05:29 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.test.js
> +import React from "react";
Ok. Fixed all cases but `SimpleTag`. I think there is no class that class that represent it.

2020-09-25 05:31 UTC, CavalcanteLucas commented
Thank you for the review. Pushed commits with requested changes. Two requests deserve attention, I left them unresolved in the comments above.

2020-09-25 05:40 UTC, CavalcanteLucas reviewed
A more appropriate title for this commit should include:

`Also refactor prop 'outline' into 'isOutline' in 'AbstractTag'`

Apologize for that.

2020-09-25 15:47 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.js
> +    onClick: PropTypes.func,
@CavalcanteLucas , I noticed that you changed all the stateful props to `is*`, but you also changed the `disabled` to `isDisabled`.
at my comment above, I said that "all stateful props that are not html attributes need to be prefixed", and since `disabled` is seen as an html attribute by most frontend devs (even if it's not used as so), it should not have been changed.

2020-09-25 15:58 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.js
>    selected = () => {
hmm, fair enough, but I see a big opportunity for a refactor here. I'll ping you on slack so we can talk about it.

2020-09-28 15:59 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    onClick: PropTypes.func,
sorry for the lack of attention! you are right
i got resistant with this idea when i was doing this, but this make way more sense.
fixed

2020-09-28 19:55 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
>    selected = () => {
thank you, fixed.

2020-09-28 21:47 UTC, CavalcanteLucas commented
Updates pushed.


There is something bothering me yet though.
Let's take `RemovableTag` as an example.
One still needs to pass `icon={icon}` just for `AbstractTag` to conditionally include a _className_ `lab-tag--has-left-icon`.
I think we could get rid of `icon` (and `thumbSrc`) in `AbstractTag`.

A solution I guess would be to conditionally include `lab-tag--has-left-icon` if `this.icon()` in `RemovableTag`.
But maybe that's not cool.

Appreciate any thoughts.

2020-09-28 21:52 UTC, CavalcanteLucas commented on labsystem/src/Tags/__snapshots__/AbstractTag.test.js.snap
> +  className="lab-tag  lab-tag--pale"
suspicious 1/3

2020-09-28 21:52 UTC, CavalcanteLucas commented on labsystem/src/Tags/__snapshots__/AbstractTag.test.js.snap
> +  className="lab-tag  lab-tag--pale"
suspicious 1/3

2020-09-28 21:53 UTC, CavalcanteLucas commented on labsystem/src/Tags/__snapshots__/AbstractTag.test.js.snap
> +  className="lab-tag  lab-tag--pale"
suspicious 3/3

2020-09-29 14:38 UTC, lucianoratamero commented on labsystem/src/Tags/__snapshots__/AbstractTag.test.js.snap
> +  className="lab-tag  lab-tag--pale"
for these suspicious ones, I'm pretty sure the reason is that you removed the ternaries that were adding the classes, but didn't pass the `className` prop from the concrete components to the abstract one, like we talked yesterday.
should be pretty simple :]

2020-09-30 21:50 UTC, CavalcanteLucas commented on labsystem/src/Tags/__snapshots__/AbstractTag.test.js.snap
> +  className="lab-tag  lab-tag--pale"
thank you, fixed

2020-09-30 21:53 UTC, CavalcanteLucas commented
Fixes pushed.

I think we're almost there. I still can't remove `icon` e  `thumbSrc` from `AbstractTag` because of `RemovableTag` and `DropdownTag`. These two have icons to the right that float aside from the border when I replicate the solution I applied for `SimpleTag` and `TogglableTag`.

2020-10-09 22:19 UTC, lucianoratamero approved these changes
LGTM!

2020-10-13 15:22 UTC, merged