Search Input UI
labcodes/labstorybook pull request #37
Opened 2020-09-14 17:43 UTC by rhannandrade

Issue: https://labcodes.atlassian.net/browse/DSYS-39
Figma: https://www.figma.com/file/Wx7jj5klQn3YsRA2XcIV3E/%F0%9F%93%9A-Design-System-MAIN?node-id=521%3A17855

This PR adds the search component, its styles, and the storybook story. It focuses on the search UI.

For this component, I had to create an AbstractSearch based on AbstractTextInput. It's used as a base for the Standard Search and Inline Search.

2020-09-14 17:46 UTC, rhannandrade commented on labsystem/scss/components/_lab-searchinput.scss
> +        margin-left:10px;
I had to change for a value that wasn't on our tokens. It was the only way to fix that feeling of a decentralized icon.

2020-09-30 21:08 UTC, debscorreia requested changes
@rhannandrade notei algumas coisas. Comentei no Jira mas vou deixar aqui tbm. 

A primeira coisa que queria comentar é sobre a branch base. A gente tinha começado a separar branches de `ui` de branches de `js` depois de tu já ter começado aqui, acredito. Ai comentamos de criar a branch `search-input-ui` com base no que tu já tavas fazendo, mas faltou criar uma `search-input-main`. Poderia seguir com a `search-input` como base, mas ia ser um pouco mais trabalhoso usar ela como base do que só fazer uma cópia da versão atual da master pra usar como base. Então isso eu já fiz mas queria falar aqui pra te explicar.

Quanto à **codigo** tenho alguns comentários 

- reparei que estamos usando no nome da classe apenas search-input sem o lab na frente. Acho que como em todos os outros componentes decidimos usar o lab seria interessante trocar para lab-search-inpu

- achei um pouco confuso que em alguns lugares dentro do search aparece um lab-input__field apesar da gente não estar usando o compontente de input, né? Fiquei se não seria o caso de criar uma classe com outro nome que extends o comportamento do lab-input__field.

- existem alguns erros no console que seria massa a gente corrigir. Deixei print no[ jira ](https://labcodes.atlassian.net/browse/DSYS-39)

Sobre **funcionalidade**, também tenho algumas sugestões:
Standard search
- Quando tem texto no input deveria aparecer o X para apagar, assim como no inline.
- reparei que quando clica no ícone o “active” nao me parece mto com o restante do que estamos fazendo. É assim mesmo? Foi um erro de merge? (mandei video no jira também)

Inline search
- Talvez quando não tem conteúdo não precise mostrar o X para apagar.

2020-09-30 21:13 UTC, debscorreia requested changes

2020-09-30 21:13 UTC, debscorreia commented on labsystem/scss/base/_titles.scss
>  }
Poderia colocar dentro da declaração anterior com 
```
h6 {
  ...

  &:first-of-type {
    ..
  }
}

2020-09-30 21:13 UTC, debscorreia commented on labsystem/scss/components/_lab-searchinput.scss
> +    .lab-input__field {
Aqui que achei um pouco estranho usar o `lab-input__field`

2020-09-30 21:13 UTC, debscorreia commented on labsystem/scss/components/_lab-searchinput.scss
> +    .search-input__icon {
Aqui antes tava `lab-icon`. Renomeei pra `search-input__icon` pra ficar mais semântico.

2020-09-30 21:13 UTC, debscorreia commented on labsystem/scss/components/_lab-searchinput.scss
> +    .lab-input__field:not(:placeholder-shown):focus ~ & {
Novamente, usamos mto o `lab-input__field`. Realmente não sei se seria mto trabalhoso trocar aqui 🤔

2020-09-30 21:13 UTC, debscorreia commented on labsystem/scss/components/_lab-searchinput.scss
> +    position: absolute;
Também mudei o nome do icon aqui.

2020-10-02 13:03 UTC, debscorreia approved these changes

2020-10-02 20:36 UTC, merged