Refactor css
labcodes/labstorybook pull request #39
Opened 2020-09-22 16:50 UTC by debscorreia

Issue link: https://labcodes.atlassian.net/browse/DSYS-116

- [x] Renomear paletas de `mineral` para `neutral`
- [x] Em `settings.scss` tornar o `$content-max-width: 900px;` → `content-max-width: 900px !default` 
- [x] Refatorar Icon para color não ser obrigatório e ele pegar a cor default de uma nova variável no settings chamada `$icon-theme`, pegando da `mineral-palette`
- [x] Cores as vezes tem hífen e em outros lugares não
- [x] Aceitar `className` sem prefixo no ícone
- [ ] Fazer pente-fino em todos os componentes buscando lugares que podem ser clicáveis ou não
- [ ] Corrigir erros de console
- [x] No scss de Toggle, as classes não estão usando o prefixo lab-
- [x] No scss de Button, as classes não estão usando o prefixo lab-

2020-09-23 17:56 UTC, CavalcanteLucas commented
All console errors have been fixed.

2020-09-23 17:59 UTC, CavalcanteLucas approved these changes

2020-09-24 14:44 UTC, lucianoratamero requested changes

2020-09-24 14:44 UTC, lucianoratamero commented on labsystem/src/Radio.js
> -    value: PropTypes.oneOfType([string, number, bool]).isRequired,
for some cases, in which you have a radio button group, we need them to have a "value" attribute, so that the browser knows which value of the group to send when POSTing. so radio groups need to have a value to conform html form specifications.

the changes on this commit (f31b7b6f6454afb19b31c020e447e2d30d841d58) need to be undone and can't be accepted =/

if there is no other way to suppress these warnings, we'll unfortunately need to live with them.

when changing the implementation this drastically, it's better for us to talk about it before making the changes :]

2020-09-24 14:44 UTC, lucianoratamero commented on labsystem/src/__snapshots__/Radio.test.js.snap
> -    value="radio1"
some of the radio button snaps were only updated at the 9c37292073fa4ed4b49cea0f967945c625d3d463 commit, and this could be a problem, because we'll need to revert the changes on the radio button commit.

there's no action to be done here; I only commented to remind us to be more vigilant before commiting when any changes of any component are made. we always need to run the tests before commiting.

2020-09-24 14:44 UTC, lucianoratamero commented on labsystem/src/Input/AbstractTextInput.js
> +    defaultValue: "",
I'm a little bit worried about passing the default value as an empty string.
we already fixed this bug in another way on the input-qa branch (@olgapinheiro just need to push it), so, in my opinion, we could undo this commit as well, or most of it (whatever is not related to the stories).

2020-09-24 15:32 UTC, CavalcanteLucas commented on labsystem/src/Radio.js
> -    value: PropTypes.oneOfType([string, number, bool]).isRequired,
ok, fixed

2020-09-24 15:33 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    defaultValue: "",
ok, fixed based on Olga's fix

2020-09-24 15:34 UTC, CavalcanteLucas commented on labsystem/src/__snapshots__/Radio.test.js.snap
> -    value="radio1"
ok, fixed.

2020-09-25 15:25 UTC, lucianoratamero requested changes

2020-09-25 15:25 UTC, lucianoratamero commented on labsystem/src/Radio.js
> +    value: PropTypes.oneOfType([string, number, bool]).isRequired,
the value prop was reintroduced in the react part, but it wasn't passed to the input (at line 73).
the HTML hasn't changed, which is the problem.

for future reference, this is one of the reasons why we have snapshot tests: to prove that something was properly rendered. in this case, the fact that the snapshots didn't change is the signal for you to find that this commit isn't 100% right.

2020-09-29 14:30 UTC, CavalcanteLucas commented on labsystem/src/Radio.js
> +    value: PropTypes.oneOfType([string, number, bool]).isRequired,
fixed

2020-09-29 17:20 UTC, lucianoratamero approved these changes

2020-09-29 18:53 UTC, merged