Tooltips - UI and React
labcodes/labstorybook pull request #42
Opened 2020-09-24 18:52 UTC by olgapinheiro

Create Tooltip component, Stories and tests.

When reviewing this PR, please take special attention to the theme color definition and to the way information is displayed / organized in the Stories.
Also, please check if any important test is missing :]

2020-09-25 15:36 UTC, lucianoratamero requested changes

2020-09-25 15:36 UTC, lucianoratamero commented on labsystem/src/Tooltip.js
> +    id: PropTypes.string.isRequired,
is the id required only because of the error message?
if so, I think we could change it to be optional and, if passed, we use the current error message, but if not, we put the text of the tooltip at the end of the message, so the dev knows which tooltip to change.

2020-09-25 16:27 UTC, falconedani requested changes
Small changes to the stylesheet and updates needed on documentation's title structure. it's using Hs for it's styling properties but it goes against our accessibility standards.

Moreover: why not using one of our components to trigger the tooltip instead of using a docs-button? (we could use an icon or a button)

2020-09-25 16:27 UTC, falconedani commented on labsystem/scss/components/_lab-tooltip.scss
> +        top: calc(-50% - 10px);
is that the distance between tooltip and element? if so, it should use a spacing token (8px).

2020-09-25 16:27 UTC, falconedani commented on labsystem/scss/components/_lab-tooltip.scss
> +    border-radius: $spacing-01;
token misuse. replace with `$radius-02`

2020-09-25 16:27 UTC, falconedani commented on stories/Tooltip.stories.mdx
> +<h4>Anatomy</h4>
Accessibility issue: we should have h1-h3 before using h4.

2020-09-28 21:26 UTC, olgapinheiro commented on labsystem/src/Tooltip.js
> +    id: PropTypes.string.isRequired,
well, not exactly because of the error message... I thought it would be bad practice to let the tooltip without an id.
If it is not necessary, I can remove it

2020-09-29 14:20 UTC, lucianoratamero approved these changes

2020-09-30 14:11 UTC, falconedani reviewed
Looks good, just remove the code used to mock buttons before merging.

2020-09-30 14:11 UTC, falconedani commented on .storybook/scss/doc-tooltip.scss
> +}
remove unnecessary code.

2020-09-30 15:58 UTC, falconedani approved these changes
✅

2020-09-30 16:17 UTC, merged