Narrow sidebar - UI
labcodes/labstorybook pull request #43
Opened 2020-09-25 14:36 UTC by rhannandrade

Issue: https://labcodes.atlassian.net/browse/DSYS-73
Figma: https://www.figma.com/file/Wx7jj5klQn3YsRA2XcIV3E/%F0%9F%93%9A-Design-System-MAIN?node-id=4979%3A4

This PR adds the Narrow Sidebar navigation component, its styles, and the storybook story. It focuses on the UI.

For this component, I had to divide in subsection to avoid storybook to stop working properly.

2020-10-13 20:11 UTC, olgapinheiro requested changes
Hey @debscorreia 
I left a few comments requesting minor changes and to better understand some points (since I'll continue this components' development in the React part)

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      padding: 16px;
Could we replace this value by a spacing variable?

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      border-radius: 0px;
I believe we shouldn't use units here

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      border-radius: 8px;
Replace these values by spacing variables

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +  margin: 24px 0 24px;
Variables

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +    border-radius: 8px;
variables

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +    margin-bottom: 4px;
variable

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      width:76%;
Hmm... why 76% so specifically?

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      padding: 4px;
variable

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      margin-left: 0px;
Unit

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      margin-right: 8px;
variable

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +        margin-right: 4px;
variable

2020-10-13 20:11 UTC, olgapinheiro commented on labsystem/scss/components/_lab-sidebar.scss
> +      border: 2px solid $item-focus-color;
I think we have variables for borders too `$border-01`

2020-10-16 13:14 UTC, debscorreia commented on .storybook/scss/doc-narrow-sidebar.scss
> +    border: 2px solid $mineral-20;
Actually the sidebar has `position: fixed` in order to be fixed on the screen on the top left corner. This is what makes possible just for the documentation to place the sidebar on the page.

2020-10-16 13:16 UTC, debscorreia commented on .storybook/scss/doc-narrow-sidebar.scss
> +  .lab-narrow-sidebar__trigger {
The trigger is the teal topbar we need to have on mobile in order to be able to "open" the sidebar.
![image](https://user-images.githubusercontent.com/5848493/96262716-925dd280-0f98-11eb-9608-d76a172d997c.png)
![image](https://user-images.githubusercontent.com/5848493/96262783-a4d80c00-0f98-11eb-8396-bd9a7b9be79f.png)

Not sure if it's clear to understand. Let me know if you have more questions :)

2020-10-16 13:22 UTC, debscorreia commented on labsystem/src/Sidebar/CollapseButton.js
> +    className: PropTypes.string,
I understand. I think this is what is happening here. I don't know how to use screenshots though ˆˆ". Can you help me?

2020-10-16 13:29 UTC, debscorreia commented on labsystem/src/Sidebar/CollapseButton.js
> +    const { className, icon, iconColor, ...rest } = this.props;
I think it shouldn't be here ^^". Removed.

2020-10-16 14:19 UTC, debscorreia commented on labsystem/scss/components/_lab-sidebar.scss
> +      border-radius: 8px;
I change to variables the `margin-right` and `border-radius`. The positioning declarations I think would be nice to have variables but they are not exactly spacing variables, so I wanted to take some more time to refactor.

2020-10-16 14:23 UTC, debscorreia commented on labsystem/scss/components/_lab-sidebar.scss
> +    border-radius: 8px;
I couldn't use variables on `margin-left: 28px;` cause we don't have this variable -.- Need to refactor this.

2020-10-19 15:32 UTC, olgapinheiro commented on .storybook/scss/doc-narrow-sidebar.scss
> +    border: 2px solid $mineral-20;
Yes, sorry, I wasn't clear here! I meant the `border: 2px solid $mineral-20;`

2020-10-19 15:33 UTC, olgapinheiro commented on .storybook/scss/doc-narrow-sidebar.scss
> +  .lab-narrow-sidebar__trigger {
Hmm, I understand now. Not sure if we could use another name to make it easier to understand... what do you think?
maybe "mobile-top-bar" or something?

2020-10-19 19:20 UTC, olgapinheiro commented on labsystem/src/Sidebar/CollapseButton.js
> +    className: PropTypes.string,
Yes, I can help you!
Normally I change the component's theme color in the settings file, then I save a screenshot of the component in the color I want, and I use this image in the part of the documentation that shows the themes, instead of a real component.
We can pair up if you prefer :] 
I'm sure we can update it really quickly together \o/

2020-10-20 19:01 UTC, debscorreia commented on labsystem/src/Sidebar/CollapseButton.js
> +    className: PropTypes.string,
Hey @olgapinheiro I took a look and actually this wasn't the case. This is the icon to collapse the documentation, so the className here isn't really needed.

2020-10-21 11:03 UTC, olgapinheiro approved these changes
Looks great to me!

2020-10-21 11:06 UTC, merged