DSYS-22/tags-qa
labcodes/labstorybook pull request #48
Opened 2020-10-23 00:00 UTC by CavalcanteLucas

**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-22 (QA 15/10)

**How to test:**
- With the LabSystem running, go to the "Component/Tag" div in the LabStoryBook, then check if everything is rendered as expected.
- Locally, from labstorybook dir, run `npm test`, then check if all tests are passing.

**Description of your solution:**
This PR fixes the documentation of Tags according to QA from 15/10/20, including "stories" and "playground". The architecture of 'TagPlayground' is refactored into a single dynamic component. Snapshots are udpated.

2020-10-26 17:39 UTC, lucianoratamero requested changes
besides the method name, I found this bug on the playground. 
![playground issue](https://user-images.githubusercontent.com/1103672/97207556-eb97e400-1798-11eb-86bb-e16860b3da3d.gif)
it could be a bug that's not related only to the 'skin', but to all props.
what I'd recommend would be to reset the state whenever changing components.

2020-10-26 17:39 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.js
> +        onKeyPress={this.handleOnClick}
hmm, I hadn't seen this method name here. :thinking: 
maybe change this method name to `handleEvents`? it's weird to use the `handleOnClick` method on the `onKeyPress` event too.
keep the prop names, it's only the component method I'm talking about.

2020-10-29 07:11 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +        onKeyPress={this.handleOnClick}
ok, fixed

2020-11-03 18:00 UTC, lucianoratamero requested changes
The playground bug that I'd reported is still present.

2020-11-04 15:52 UTC, CavalcanteLucas commented
Oh! I'm sorry.. I missed one line when refactoring the solution. Thank you for noticing!! Fixed.

2020-11-06 18:11 UTC, lucianoratamero approved these changes

2020-11-06 20:57 UTC, merged