DSYS-18/alerts-js
labcodes/labstorybook pull request #49
Opened 2020-10-24 00:55 UTC by CavalcanteLucas

**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-18

**How to test:**
- With the LabSystem running in `localhost`, go to the "Component/System Messages" div the main page, then check if everything is rendered as expected.
- Locally, from `labstorybook` dir, run npm test, then check if all tests are passing.

**Description of your solution:**
This PR implements the JS behavior of Alerts and Banners (scroll handler, button response etc.). It also introduces a 'SystemMessagesPlayground' component to the documentation on 'SystemMessages.stories'. Small fixes to Stories and CSS are included. Snapshots are updated.

2020-10-26 18:37 UTC, lucianoratamero commented on labsystem/src/Alert.js
> +      <TextButton size="normal" skin="dark" text={buttonProps.text} />
no need to change it here, but just to let you know: there's a way you can take only the text like this:
`const { buttonProps: { text } } = this.props;`
this would create a variable called `text` with the content of `this.props.buttonProps.text`.

2020-10-26 18:42 UTC, lucianoratamero requested changes

2020-10-26 18:42 UTC, lucianoratamero commented on labsystem/src/Alert.test.js
> +            onClicl: () => {},
typo

2020-10-26 18:42 UTC, lucianoratamero commented on labsystem/src/Alert.test.js
> +});
I think we should also have a test that made sure that the `buttonProps.onClick` was called passing the event when the alert button was clicked. same thing for banners.

2020-10-26 18:42 UTC, lucianoratamero commented on stories/SystemMessages.stories.mdx
> +  <img src="docs/system-messages/use-example.png" />
this may not be a question for you, but for @falconedani : should this jira print be here? I mean, this could be a privacy problem :thinking:

2020-10-27 15:49 UTC, CavalcanteLucas commented on labsystem/src/Alert.js
> +      <TextButton size="normal" skin="dark" text={buttonProps.text} />
thank you ! fixed

2020-10-27 15:49 UTC, CavalcanteLucas commented on labsystem/src/Alert.test.js
> +            onClicl: () => {},
thank you, fixed!

2020-10-27 17:14 UTC, CavalcanteLucas commented on labsystem/src/Alert.test.js
> +});
you're right, fixed

2020-10-27 17:39 UTC, CavalcanteLucas commented
Ospy, the last commit `Add tests for clicking in 'Alert' and 'Banner'` was squashed in the history, but changes are there. :+1:

2020-10-27 18:46 UTC, lucianoratamero approved these changes

2020-10-27 19:38 UTC, CavalcanteLucas commented on stories/SystemMessages.stories.mdx
> +  <img src="docs/system-messages/use-example.png" />
should I wait it for merge?

2020-10-29 15:55 UTC, falconedani commented on stories/SystemMessages.stories.mdx
> +  <img src="docs/system-messages/use-example.png" />
replaced

2020-10-29 19:16 UTC, merged