DSYS-73: Narrow sidebar js
labcodes/labstorybook pull request #56
Opened 2020-11-16 21:06 UTC by lucianoratamero

**Link to task:** https://labcodes.atlassian.net/browse/DSYS-73

**Details:**
The components that this PR contains are intentionally different from the specs, since it would take a while to refactor them. 
We focused on testing and functionality instead.
There are some small details missing and needed to be refactored, but they're already considered on the [refactor task](https://labcodes.atlassian.net/browse/DSYS-123).

2020-11-20 21:37 UTC, olgapinheiro requested changes
Hey, seems to be working fine!
I added a few small comments. Most of them are totally optional, except for the one about the coral vivid example.

2020-11-20 21:37 UTC, olgapinheiro commented on stories/NarrowSidebarVivid.stories.mdx
> +            <NarrowSidebar.Item onClick={() => {}} icon="calendar" label="Teste" />
missing `isActive` in the `coral` example

2020-11-20 21:37 UTC, olgapinheiro commented on playgrounds/NarrowSidebarPlayground.js
> +                  value={itemIcon}
What do you think of using a Select input to choose the `itemIcon` and the `footerButtonIcon`?
I was going to do that, but didn't have time

2020-11-20 21:37 UTC, olgapinheiro commented on playgrounds/NarrowSidebarPlayground.js
> +          ) : null}
Maybe it would be good to add some padding between the avatar props and the `footerButton` props?

2020-11-24 17:50 UTC, lucianoratamero commented on playgrounds/NarrowSidebarPlayground.js
> +                  value={itemIcon}
because of the due date, I'll not work much on more playground improvements, sorry about that =/

2020-11-25 23:06 UTC, debscorreia approved these changes

2020-11-26 19:30 UTC, merged