Accessibility Statement
labcodes/labstorybook pull request #61
Opened 2020-11-25 22:05 UTC by falconedani

Added an accessibility section in Getting Started with an overview about what accessibility means for the Design System and which methods we are using for testing.

Also updated the changelog with an accessibility column and proposed a new convention for the status with descriptions.

2020-11-26 01:35 UTC, debscorreia requested changes
@falconedani , I left some comments here and explained a little better on Jira https://labcodes.atlassian.net/browse/DSYS-139 , but nothing big. Let me know if you need help :)

2020-11-26 01:35 UTC, debscorreia commented on stories/ChangeLog.stories.mdx
> +React: to understand which components are available on Figma's Design System or are mapped on the roadmap.
React and Design text are the same. Is that intentional? Can be confusing.

2020-11-26 11:14 UTC, falconedani commented on stories/Accessibility.stories.mdx
> +  <p>From <a src="https://www.w3.org/WAI/fundamentals/accessibility-principles/">W3C's Web Accessibility Initiative</a></p>
Fixed the src/href mistake, sorry about that.

The Accessibility principles were formulated by W3C, they are an umbrella to cover most accessibility issues.

2020-11-26 11:18 UTC, falconedani commented on stories/ChangeLog.stories.mdx
> +React: to understand which components are available on Figma's Design System or are mapped on the roadmap.
No, it wasn't. Thanks for noticing. Fixed.

2020-11-26 11:19 UTC, falconedani commented on stories/Accessibility.stories.mdx
> +  <li><a src="https://www.w3.org/TR/WCAG21/">Web Content Accessibility Guidelines</a></li>
I was sure I did it 🤔  It's fixed anyway

2020-11-26 11:19 UTC, falconedani commented on stories/Accessibility.stories.mdx
> +  <li>Robust content and reliable interpretation</li>
I was sure I did it 🤔  It's fixed anyway

2020-11-26 11:19 UTC, falconedani commented on stories/Accessibility.stories.mdx
> +  <li><a src="https://labcodes-wiki.herokuapp.com/best-practices/accessibility/">Labcodes' Web Accessibility Guide</a></li>
Done

2020-11-26 19:08 UTC, debscorreia approved these changes

2020-12-01 17:21 UTC, lucianoratamero approved these changes
LGTM!

2020-12-01 18:24 UTC, merged