Fix toggle
labcodes/labstorybook pull request #66
Opened 2020-12-02 16:44 UTC by falconedani

Renamed `theme` pro for `color` to be consistent with other components.

2020-12-02 17:04 UTC, lucianoratamero requested changes
If you have any questions, ping me on slack! :]

2020-12-02 17:04 UTC, lucianoratamero commented on labsystem/src/Toggle.js
> +import PropTypes, { oneOf } from "prop-types";
Here, instead of importing the `oneOf` from "prop-types",  you can just use `PropTypes.oneOf` on line 7 and remove this import :]

2020-12-02 17:04 UTC, lucianoratamero commented on labsystem/src/__snapshots__/Toggle.test.js.snap
> +          lab-toggle--teal
I'm pretty sure this snapshot shouldn't have changed, since this test verifies that the `Toggle renders as expected when passing a different theme 1`.
What I think is going on is that you may need to change all mentions of the `theme` prop at the `Toggle.test.js` file and rename them to `color`. That way, this snapshot should revert to rendering `lab-toggle--purple`.

2020-12-02 18:27 UTC, falconedani commented on labsystem/src/Toggle.js
> +import PropTypes, { oneOf } from "prop-types";
solved

2020-12-02 18:27 UTC, falconedani commented on labsystem/src/__snapshots__/Toggle.test.js.snap
> +          lab-toggle--teal
solved

2020-12-03 17:21 UTC, lucianoratamero approved these changes
LGTM!

2020-12-03 19:19 UTC, merged