DSYS-23: Dialogs
labcodes/labstorybook pull request #67
Opened 2020-12-03 21:12 UTC by CavalcanteLucas

**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-23

**Description:**
This PR implements the JS behavior of `StandardDialog` and `MessageDialog`. It introduces a `DialogPlayground.js` for the documentation on `Dialog.stories.mdx`. It also introduces the backbone for styling in `_lab-dialog.scss`.

2020-12-04 16:36 UTC, lucianoratamero requested changes
After fixing, please add to the jira task a comment to make it clear that, for the UI part, they'll need to reinstall the dependencies inside the labsystem folder because of the focus trap.

It would be nice to document how the swipe works as well, telling people to use tme mobile emulator on dev tools and that the swipe has a bit of a "resistance", needing to swipe more than 75px to work.

2020-12-04 16:36 UTC, lucianoratamero commented on labsystem/src/Dialog/MessageDialog.js
> +          <div className="lab-dialog__content--message">{content}</div>
the two class names above here only have the modifier. please add the element as well, like this:

```suggestion
          <div className="lab-dialog__title lab-dialog__title--message">{title}</div>

          <div className="lab-dialog__content lab-dialog__content--message">{content}</div>
```

2020-12-04 19:41 UTC, CavalcanteLucas commented on labsystem/src/Dialog/MessageDialog.js
> +          <div className="lab-dialog__content--message">{content}</div>
thank you, fixed.

2020-12-04 20:12 UTC, CavalcanteLucas commented
Applied requested changes, and updated PR description.

2020-12-08 15:51 UTC, falconedani approved these changes
LGTM

2020-12-10 21:17 UTC, lucianoratamero approved these changes

2020-12-10 22:24 UTC, merged