DSYS-182: Button playground
labcodes/labstorybook pull request #70
Opened 2020-12-10 22:22 UTC by CavalcanteLucas

**Link to task**
https://labcodes.atlassian.net/browse/DSYS-182

**Description**
This PR implements the `ButtonPlayground` component, used in `Button.stories.mdx`. Also, few small details are refactored across the codebase towards uniformization. For example, `e` as an argument of React methods are replaced by `event`. Occurences of `<>` are replaced by `<React.Fragment>` etc.

**How to test**
Go to `Button` page in the _Stories_. Check if there is a Playground section. Try different input combination.

Notes:
- `light` buttons can't be seen with a white background;
- `Checkbox` has been used instead of `Toggle` due to an easier documentation.

2020-12-10 23:54 UTC, debscorreia commented
We noticed that the branch `playground-ui` wasn't merged yet on `master`. So we merged and then needed to do a rebase with `master` to integrate the changes.

2020-12-11 18:56 UTC, lucianoratamero requested changes
The code looks good, but there are two things you need to keep in mind:

- Dani has made a lot of considerations on the jira ticket
- this PR has WAY more than just the playground. I won't ask you to migrate changes to other branches, since it would be counterproductive, but I'll need to ask you to take a look at all the tickets that are still open and update them  removing the topics you've fixed here. One example is that some of the changes here solve most of the `fix-button` task, but it can't be closed, because one of the topics of `fix-buttons` wasn't covered.

It's preferrable that this situation doesn't happen, so, please, be careful about what you commit for which task. It will give everyone a little bit of a headeache just to track what you solved here relative to what's on the jira tickets.

When you finish updating the tasks on jira, ask me to review it again, so I approve the PR. :]

2020-12-11 18:59 UTC, CavalcanteLucas commented
OK, understood! I'll track what's left from `fix-button` as well.

2020-12-11 19:01 UTC, lucianoratamero commented
> OK, understood! I'll track what's left from `fix-button` as well.

Just be careful, since it's not only on fix-buttons. You'll need to look at all pending task, probably. =/

2020-12-11 19:03 UTC, CavalcanteLucas commented
> > OK, understood! I'll track what's left from `fix-button` as well.
> 
> Just be careful, since it's not only on fix-buttons. You'll need to look at all pending task, probably. =/

OK, I will

2020-12-14 14:57 UTC, falconedani requested changes

2020-12-14 14:57 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonVariationPropChange}
add defaultChecked

2020-12-15 16:47 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
> +  <h4>Interactive Demo</h4>
ok, fixed.

2020-12-15 16:53 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +              <br />
i think so, because i'm using `<span>` (not `<div>`) for each `lab-playground__item`

2020-12-15 16:54 UTC, CavalcanteLucas commented on stories/Tooltip.stories.mdx
> +            color="teal-60"
it' ok, no conflicts will appear on merge

2020-12-15 16:55 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
> +
ok, fixed.

2020-12-16 21:59 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +              <br />
If we want a multiline block, it's a better practice to either use `div` or break them in smaller blocks with multiple `span` tags.

2020-12-18 19:31 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonVariationPropChange}
`defaultChecked` is not working. the solution i used was:

```
                checked={currentComponent === "Button"}
```

2020-12-18 19:36 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +              <br />
just checked that <divs> are not breaking lines.. <br> would still be needed.
any suggestions ?

2020-12-18 19:37 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
> +
by the way, i think there should be a task to fix this over all stories.. it seem's the old way is the widespread approach

2020-12-18 19:37 UTC, CavalcanteLucas commented on stories/Buttons.stories.mdx
> +
i'm actually marking this as 'unsolved'

2020-12-18 19:38 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonSizePropChange}
same as above, defaultChecked is not working. the solution i used was:

```
                checked={currentComponent === "Button"}
```

2020-12-18 19:42 UTC, CavalcanteLucas commented
had to push-force due to rebase. single last commit contains required changes.

2020-12-21 14:13 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonVariationPropChange}
The defaultChecked should be fixed soon, I'd keep it as it should be and wait for the fix.
What do you say @lucianoratamero ?

2020-12-21 14:48 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +              <br />
We are using `display: inline-block` for playground items, we may change it for `display: flex` with `flex-direction: column` and updating margins to `margin: $spacing-05 $spacing-02;`.

Removing `<br />` and replacing `<span>` for `<div>` would look like:
![image](https://user-images.githubusercontent.com/56659186/102788907-2164dd80-4382-11eb-8158-fb3852b0fe2f.png)

(I've also used `<p><strong>` on toggle labels)

It does interfere with other playgrounds since some still have things to be worked on (like use of `<br />`), but I think it's a better approach.

What do you think?

2020-12-21 14:49 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonSizePropChange}
I've unresolved since we are still working on it.

2020-12-21 14:53 UTC, falconedani commented on stories/Buttons.stories.mdx
> +
I had worked on this on that weird merge we made :/

I've added to https://labcodes.atlassian.net/browse/DSYS-141

2020-12-21 15:03 UTC, falconedani requested changes

2020-12-21 15:03 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +              label="full width"
```suggestion
```

We don't have this prop.

2020-12-21 15:03 UTC, falconedani commented on playgrounds/ButtonPlayground.js
> +              label="disabled"
```suggestion
```

We don't have this prop.

2020-12-21 16:29 UTC, lucianoratamero commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonVariationPropChange}
yup, agreed!

2020-12-21 17:12 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +              label="full width"
ok, fixed.

2020-12-21 17:12 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +              label="disabled"
ok, fixed.

2020-12-21 17:20 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonVariationPropChange}
ok, fixed.

2020-12-21 17:25 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +                onChange={this.handleButtonSizePropChange}
fixed

2020-12-21 17:36 UTC, CavalcanteLucas commented on playgrounds/ButtonPlayground.js
> +              <br />
thank you, fixed.

2020-12-21 17:39 UTC, CavalcanteLucas commented
applied requested fixes

2020-12-21 17:40 UTC, falconedani approved these changes
🏆

2020-12-21 17:53 UTC, merged