DSYS-184: Add description to prop types for all components
labcodes/labstorybook pull request #73
Opened 2020-12-16 01:00 UTC by CavalcanteLucas

**Link to task**
https://labcodes.atlassian.net/browse/DSYS-184

**Description**
This PR adds 222 prop type description for all 33 components or sub-components. In the description, component names are capitalized like `Search` (vs. the action/verb "search").

**How to test**
- With the storybook running, check each prop description for every component.
- Look for the pattern `/** */` on the Design System directory. You can use Visual Studio Code's search system or, from the terminal, run the following command:
```
 grep -rn "\/\*\*\ \*\/" labsystem/ 
 ```
 Then check if there are any descriptions missing.
 
 ---
 Notes:
 
 Currrently, there are some descriptions missing. The output of the `grep` command above should output:
 ```
 labsystem/src/Radio.js:24:    /** */
labsystem/src/Radio.js:26:    /** */
labsystem/src/Input/AbstractTextInput.js:45:    /** */
labsystem/src/Icon.js:66:    /** */
labsystem/src/Badge.js:49:    /** */
labsystem/src/Checkbox.js:27:    /** */
labsystem/src/Checkbox.js:29:    /** */
```
This is yet to be solved.  I leave some notes for further discussion:

- `AbstractTextInput.js`: shouldn't the prop `type` be required?
- `Badge/Item`: the prop `className` seem to be unused (it occours similiarly in `Checkbox` and `Toggle`).
- `Checkbox/Radio`: I couldn't describe the prop `value`. It seems to be unused and undocumented. (One more thing, there is a `Playground` inside a `Canvas` in the Stories)
- `Toggle`: shouldn't <input> have a `name` (like `Checkbox` and `Radio`)?

2020-12-16 16:49 UTC, lucianoratamero commented
@CavalcanteLucas , could we schedule a meeting for tomorrow or friday so we can talk about your comments and see what's left to document?

2020-12-18 14:25 UTC, nenispng requested changes

2020-12-18 14:25 UTC, nenispng commented on labsystem/src/Checkbox.js
> +    /** Text that will be rendered as the Checkbox's label. */
```suggestion
    /** This is the checkbox's label. */
```

2020-12-18 14:25 UTC, nenispng commented on labsystem/src/Checkbox.js
> +    /** Disables the Input component, including functionality and style. */
```suggestion
    /** Disables the checkbox. */
```

2020-12-18 14:25 UTC, nenispng commented on labsystem/src/Checkbox.js
> +    /** Callback to be executed when the Checkbox is clicked. */
```suggestion
    /** Callback action to be executed when the Checkbox is clicked. */
```

2020-12-18 14:25 UTC, nenispng commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Text that will serve as placeholder if the Input field is empty. */
```suggestion
    /** The placeholder text when Input field is empty. */
```

2020-12-18 14:25 UTC, nenispng commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Text that will be rendered as the Input's label. */
```suggestion
    /** The Input's text label. */
```

2020-12-18 14:25 UTC, nenispng commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Disables the Input component, including functionality and style. */
```suggestion
    /** Sets the text input to disabled, refusing interactions. */
```

2020-12-18 17:35 UTC, falconedani commented on labsystem/src/Checkbox.js
> +    /** */
```suggestion
    /** Add a class name to make custom changes */
```

2020-12-18 17:35 UTC, falconedani commented on labsystem/src/Icon.js
> +    /** */
```suggestion
    /** Add a class name to make custom changes */
```

we should've been using this more often, actually

2020-12-18 20:07 UTC, falconedani requested changes
I couldn't finish all the components but decided to send the review so you can start working on it

2020-12-19 00:19 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Children component. */
I didn't see any references on the documentation, including stories and playground, nor exapmles from other components :/ I don't know to be honest

2020-12-19 00:25 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Defines a default value for the Input initialization. */
I think the `placeholder` is just to render something on the `<input>` when the `value` parameter is empty, while the `defaultValue` was the found solution to set an initial **value** for the `value` variable.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Alert.js
> +    /** Ojbect with information about the Alert's button. */
ok, fixed.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.js
> +    /** */
i was unsure as well. updates were made on this line after conversation with @lucianoratamero . i will mark here as solved regarded it is now obsolete.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Text that will be rendered inside the Input field. */
see comment above

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Input/EmailInput.js
ok, solved.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Input/PasswordInput.js
ok, solved.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Input/TextInput.js
ok, solved.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Search/AbstractSearch.js
ok, solved.

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Search/InlineSearch.js
ok, solved

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Search/StandardSearch.js
ok, solved

2020-12-19 02:32 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** HMTL className of a concrete Tag to be enriched. */
ok, fixed

2020-12-19 02:40 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/Body.js
> +    /** Target component to which the Sidebar should be applied upon. */
this class is the `Body` of it's `children` component

maybe @lucianoratamero could help me clarify that

2020-12-19 02:40 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/Footer.js
> +    /** Target component to which the Sidebar should be applied upon. */
same case of `Body`. This class implements the `Footer` of it's `children` prop (which is another component).

2020-12-19 02:40 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/Header.js
> +    /** Target component to which the Sidebar should be applied upon. */
same case of `Body` and `Footer`. This is the `Header` of some `children` component passed to itself as a prop

2020-12-19 02:40 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/NarrowSidebar.js
> +    /** Target component to which the Sidebar should be applied upon. */
see comments above

2020-12-21 15:07 UTC, falconedani commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Children component. */
@lucianoratamero could you help here?

2020-12-21 18:11 UTC, falconedani commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Children component. */
On Text Inputs the placeholder is displayed on top of the label, so we have removed from the code base.

2020-12-21 18:20 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Children component. */
prop unused. removing from codebase.

2020-12-21 20:04 UTC, falconedani requested changes
Some updates suggested.

2020-12-21 20:04 UTC, falconedani commented on labsystem/src/Sidebar/NarrowSidebar.js
> +    /** Target component to which the Sidebar should be applied upon. */
```suggestion
    /** Components that will be rendered in the NarrowSidebar (Header, Item, Logotype, etc). */
```

2020-12-21 20:04 UTC, falconedani commented on labsystem/src/Tags/DropdownTag.js
> +    /** Text that will be rendered inside the Tag. */
```suggestion
    /** This is the Tag's text. */
```

2020-12-22 14:45 UTC, falconedani requested changes
Added a new suggestion

2020-12-22 14:45 UTC, falconedani commented on labsystem/src/Radio.js
> +    /** Text that will specify the HTML `name` attribute of an <input> element. */
```suggestion
    /** Text that will specify the HTML `name` attribute of an <input> element. It's used to group a set of Radios. */
```

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Text that will specify the HTML type attribute of an <input> element. */
ok, fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Sets the text input to disabled, refusing interactions. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> +    /** Text that will be rendered inside the Input field. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/EmailInput.js
> +    /** Sets the text input to disabled, refusing interactions. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/EmailInput.js
> +    /** Text that will be rendered inside the Input field. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/EmailInput.js
> +    /** Defines which symbol to show. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/EmailInput.js
> +    /** Defines the color of the displayed icon. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/PasswordInput.js
> +    /** Sets the text input to disabled, refusing interactions. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Input/PasswordInput.js
> +    /** Text that will be rendered inside the Input field. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Radio.js
> +    /** Text that will specify the HTML `name` attribute of an <input> element. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Search/AbstractSearch.js
> +    /** The placeholder text when the Search field is empty. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Search/InlineSearch.js
> +    /** The placeholder text when the Search field is empty. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Search/StandardSearch.js
> +    /** The placeholder text when the Search field is empty. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/Body.js
> +    /** Target component to which the Sidebar should be applied upon. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/Footer.js
> +    /** Target component to which the Sidebar should be applied upon. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/Header.js
> +    /** Target component to which the Sidebar should be applied upon. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Sidebar/NarrowSidebar.js
> +    /** Target component to which the Sidebar should be applied upon. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** Text that will be rendered inside the Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** Color of the rendered Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** Defines if the Tag has an outline style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** Disables the Tag component, including functionality and style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** Callback to be executed when the Tag is clicked. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.js
> +    /** Text that will be rendered inside the Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.js
> +    /** Color of the rendered Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.js
> +    /** Defines if the Tag has an outline style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.js
> +    /** Disables the Tag component, including functionality and style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/DropdownTag.js
> +    /** Callback to be executed when the Tag is clicked. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/RemovableTag.js
> +    /** Text that will be rendered inside the Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/RemovableTag.js
> +    /** Source of the thumb to be rendered. Won't render a thumb if not passed to the component. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/RemovableTag.js
> +    /** Color of the rendered Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/RemovableTag.js
> +    /** Defines if the Tag has an outline style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/RemovableTag.js
> +    /** Disables the Tag component, including functionality and style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/SimpleTag.js
> +    /** Text that will be rendered inside the Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/SimpleTag.js
> +    /** Color of the rendered Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/SimpleTag.js
> +    /** Defines if the Tag has an outline style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +    /** Text that will be rendered inside the Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +    /** Color of the rendered Tag. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +    /** Defines if the Tag has an outline style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +    /** Disables the Tag component, including functionality and style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +    /** Callback to be executed when the Tag is clicked. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +    /** Defines if the Tag is switched on. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Toggle.js
> +    /** Disables the Toggle component, including functionality and style. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Toggle.js
> +    /** Defines a default value for the Toggle initialization. */
fixed

2020-12-23 19:38 UTC, CavalcanteLucas commented on labsystem/src/Toggle.js
> +    /** Callback to be executed when the Toggle is clicked. */
fixed

2020-12-23 20:26 UTC, CavalcanteLucas commented on labsystem/src/Tags/SimpleTag.js
> +    /** Disables the Tag component, including functionality and style. */
ok, fixed.

2020-12-23 21:21 UTC, falconedani requested changes
I think that after these final suggestions we are ready to merge. Sorry for the endless corrections.

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/AbstractSearch.js
> +    /** Sets the text input to disabled, refusing interactions. */
```suggestion
    /** Disables the Search. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/AbstractSearch.js
> +    /** Callback action to be executed when the Search default value changes. */
```suggestion
    /** Action to be executed when the Search default value changes. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/AbstractSearch.js
> +    /** Callback to be executed when the search is performed. */
```suggestion
    /** Action to be executed when the search is performed. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/AbstractSearch.js
> +    /** Callback to be executed when the Search is cleared out. */
```suggestion
    /** Action to be executed when the Search field is cleared out. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/InlineSearch.js
> +    /** Sets the text input to disabled, refusing interactions. */
```suggestion
    /** Disables the Search. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/InlineSearch.js
> +    /** Callback action to be executed when the Search default value changes. */
```suggestion
    /** Action to be executed when the Search default value changes. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/InlineSearch.js
> +    /** Callback to be executed when the search is performed. */
```suggestion
    /** Action to be executed when the search is performed. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/InlineSearch.js
> +    /** Callback to be executed when the Search is cleared out. */
```suggestion
    /** Action to be executed when the Search is cleared out. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/StandardSearch.js
> +    /** Sets the text input to disabled, refusing interactions. */
```suggestion
    /** Disables the Search. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/StandardSearch.js
> +    /** Callback action to be executed when the Search default value changes. */
```suggestion
    /** Action to be executed when the Search default value changes. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/StandardSearch.js
> +    /** Callback to be executed when the search is performed. */
```suggestion
    /** Action to be executed when the search is performed. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Search/StandardSearch.js
> +    /** Callback to be executed when the Search is cleared out. */
```suggestion
    /** Action to be executed when the Search is cleared out. */
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Tags/AbstractTag.js
> +    /** HTML tabIndex, used to avoid Tag from being selected with TAB key, if "-1". */
```suggestion
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Tags/AbstractTag.js
> +    tabIndex: "0",
```suggestion
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Tags/AbstractTag.js
>      tabIndex: PropTypes.string,
```suggestion
```

2020-12-23 21:21 UTC, falconedani commented on labsystem/src/Tags/AbstractTag.js
> +    /** HTML tabIndex, used to avoid Tag from being selected with TAB key, if "-1". */
@CavalcanteLucas you missed this one. Please remove all mentions of tabIndex from the component

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/AbstractSearch.js
> +    /** Sets the text input to disabled, refusing interactions. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/AbstractSearch.js
> +    /** Callback action to be executed when the Search default value changes. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/AbstractSearch.js
> +    /** Callback to be executed when the search is performed. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/AbstractSearch.js
> +    /** Callback to be executed when the Search is cleared out. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/InlineSearch.js
> +    /** Sets the text input to disabled, refusing interactions. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/InlineSearch.js
> +    /** Callback action to be executed when the Search default value changes. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/InlineSearch.js
> +    /** Callback to be executed when the search is performed. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/InlineSearch.js
> +    /** Callback to be executed when the Search is cleared out. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/StandardSearch.js
> +    /** Sets the text input to disabled, refusing interactions. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/StandardSearch.js
> +    /** Callback action to be executed when the Search default value changes. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/StandardSearch.js
> +    /** Callback to be executed when the search is performed. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Search/StandardSearch.js
> +    /** Callback to be executed when the Search is cleared out. */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    /** HTML tabIndex, used to avoid Tag from being selected with TAB key, if "-1". */
fixed

2020-12-23 22:55 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
> +    tabIndex: "0",
fixed

2020-12-23 23:00 UTC, CavalcanteLucas commented on labsystem/src/Tags/AbstractTag.js
>      tabIndex: PropTypes.string,
fixed

2020-12-28 13:08 UTC, falconedani approved these changes
🙌

2020-12-28 15:16 UTC, merged