Docs setup contribute
labcodes/labstorybook pull request #74
Opened 2020-12-16 16:34 UTC by lucianoratamero

**Link to task:** https://labcodes.atlassian.net/browse/DSYS-89
**Staging app:** https://docs-setup-contribute--labstorybook-master.netlify.app/

This PR adds Setup and How to Contribute stories, as well as README files for the storybook and DS.

2020-12-16 21:54 UTC, falconedani approved these changes
I think it’s ok, but I was wondering if it wouldn’t be better to create a `Theme` story under "base” with the section you wrote to make it easier to find.

Also, is Storybook really needed to just use the design system? Wouldn’t it be a better fit as a section in How to Contribute?

Minor thingy: could you add target blank so that links open in a different tab? It was very annoying for me.

2020-12-17 20:27 UTC, lucianoratamero commented
@falconedani about your points:

1- I'm not sure I agree with your point. :thinking: the theming is 100% related to how we would use the DS' code in an outside project, so, as a developer, it makes more sense for me to have it together with the other instructions on how to set it up. but I do want to understand: why did you think it would be better to put it under "Base" instead? Beucase there may be other solutions, depending on the problem.

2- To answer your question: no, we don't need the storybook to use the DS; but we need the DS to use the storybook. Maybe having both set up instructions together in the same page gave you the impression that they are coupled together, though. Was that the problem? 
If so, I don't think the solution would be to put it on How to Contribute; the whole project is based on storybook, and putting the set up instructions inside the How to Contribute could be even more confusing. My suggestion would be for us to create a separate story for the Confetti instructions. Maybe we could even create their own section of the sidebar, so that we could put the set up instructions for Storybook, Confetti and How to Contribute. What do you think?

3- Sure, working on it!

2020-12-17 20:29 UTC, lucianoratamero commented
PS: for these cases, in which things are still confusing and changes will be needed, it's better to not approve the PR. Approving it gives us the idea that it's ready to be merged, when it's not the case. It's not a problem to reject a PR, even if the code is alright. :]

2020-12-21 15:49 UTC, falconedani requested changes
Tiny things to adjust

2020-12-21 15:49 UTC, falconedani commented on stories/base/ChangeLog.stories.mdx
> +<Meta title="Base/Changelog" />
```suggestion
<Meta title="Getting started/Changelog" />
```

I felt it lost in the base menu, please move it back to getting started

2020-12-21 15:49 UTC, falconedani commented on stories/getting-started/How to Contribute.stories.mdx
> +      <p>If you're not an active developer on the Confetti team, to start contributing, please fork our <a target="_blank" rel="noopener" href="https://github.com/labcodes/labstorybook/">source code
```suggestion
      <p>If you're not an active developer on the Confetti team, to start contributing, please fork our <a target="_blank" rel="noopener" href="https://github.com/labcodes/labstorybook/">source code on Github</a>. If you are, you'll already have access to the main repo, so forget about forks. Currently, the codebase contains both the <a target="_blank" rel="noopener" href="/?path=/docs/getting-started-setup-storybook--page">Storybook</a> and the <a target="_blank" rel="noopener" href="/?path=/docs/getting-started-setup-confetti--page">Confetti's</a> own source code, so please read the docs.</p>
```

2020-12-21 15:49 UTC, falconedani commented on stories/getting-started/How to Contribute.stories.mdx
> +      <p>The only main rule is that <code>master</code> should always, <strong>always</strong> stable. For that, be sure to run the tests (details on how to are in the <a target="_blank" rel="noopene
```suggestion
      <p>The only main rule is that <code>master</code> should always, <strong>always</strong> be stable. For that, be sure to run the tests (details on how to are in the <a target="_blank" rel="noopener" href="/?path=/docs/getting-started-setup--page">Setup docs</a>) before pushing your code and never push with the <code>--no-validate</code> flag, unless specifically being asked to.</p>
```

2020-12-21 16:11 UTC, lucianoratamero commented
Done @falconedani ! Merging :]

2020-12-21 16:11 UTC, merged