Dialogs UI
labcodes/labstorybook pull request #75
Opened 2020-12-16 18:24 UTC by falconedani

**Staging:** https://dialogs-ui--labstorybook-master.netlify.app/?path=/docs/components-dialog--page
**Jira issue:** https://labcodes.atlassian.net/browse/DSYS-23
**Details**
Add styles with animations for both dialog types. Please take a closer look at animations and the method used to position the components. I could only achieve animations for when the open, but not when closing. Any tips are appreciated.

2020-12-23 17:44 UTC, lucianoratamero requested changes
both the styles and the code for this PR are kind of weird.
too many things to talk about here, though.
maybe shouwl we pair up on this, @falconedani ?

2020-12-23 19:28 UTC, falconedani reviewed
Changes needed on lab-icon class use

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +    .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +    .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +  .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +    .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +  .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +    .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +    .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +  .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +    .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/scss/components/_lab-dialog.scss
> +  .lab-icon {
update to a more specific class

2020-12-23 19:28 UTC, falconedani commented on labsystem/src/Dialog/StandardDialog.js
> +            <Icon type="collapse-open" />
add classname

2020-12-28 18:13 UTC, closed without merging

2020-12-28 18:13 UTC, lucianoratamero commented
since the git tree is messed up, we'll create a new branch for these changes