DSYS-179: Fix prop types
labcodes/labstorybook pull request #76
Opened 2020-12-17 18:09 UTC by CavalcanteLucas

**Link to task**
https://labcodes.atlassian.net/browse/DSYS-178

**Description**
This PR replaces the deafult props of all props of type _function_. Instead of `undefined` they are now set to `() => {}`. This change led to a required a small refactoring in `AbstractTextInput` regarding its subcomponent `TrailingIcon`. Snapshots are slightly updated to reflect changes on these components.  

**How to test**
With the story book running, go to the `Text Input` section. In the playground, _disable_ the input then click on the trailing icon of `PasswordInput`. Check if nothing happens.

2020-12-17 20:51 UTC, lucianoratamero requested changes

2020-12-17 20:51 UTC, lucianoratamero commented on labsystem/src/Input/AbstractTextInput.js
> -    }
Here, you should've only removed the if, but kept the onChange call. Removing the onChange call completely inutilizes the input, since its value can't be synced with a parent component anymore.
In fact, we're missing a test checking that when the input changes, the onChange prop is called with the event. It would've prevented you from removing this call here. :thinking: 

Please, add the test (something like this: https://github.com/labcodes/labstorybook/blob/master/labsystem/src/Checkbox.test.js#L128) and call the onChange prop here again.

2020-12-17 20:51 UTC, lucianoratamero commented on labsystem/src/Input/AbstractTextInput.js
> +  );
Waaaaay better, thanks for the refactor!

2020-12-18 23:57 UTC, CavalcanteLucas commented on labsystem/src/Input/AbstractTextInput.js
> -    }
found that there was a test for this already, but it was not quite working as expected i guess. this is the essential fix i've made:

```
-    inputElement
-      .at(0)
-      .simulate("change", {
-        target: {
-          value: "My new value",
-          validity: { valid: true },
-          setCustomValidity: jest.fn(),
-        },
-      });
-
+    expect(mockOnChange).not.toBeCalled();
+    inputElement.simulate("change", {
+      target: {
+        value: "My new value",
+        validity: { valid: true },
+        setCustomValidity: jest.fn,
+      },
+    });
+    expect(mockOnChange).toBeCalled();
```

2020-12-23 17:32 UTC, lucianoratamero approved these changes

2020-12-23 18:18 UTC, merged