DSYS-157 & DSYS-161: Fix tests
labcodes/labstorybook pull request #89
Opened 2020-12-30 22:55 UTC by CavalcanteLucas

**Link to tasks**
https://labcodes.atlassian.net/browse/DSYS-157
https://labcodes.atlassian.net/browse/DSYS-161

**Description**
This PR implements tests for checking full width buttons.
Also in this PR, all references to `component.states()` are removed from the test codebase. That includes 17 tests across 3 test files:
- 7 times for `Checkbox` (to `localChecked`);
- 7 times for `Toggle` (to `localValue`);
- 2 times for `PasswordInput` (to `showPassword`).
In the files mentioned above, variables named as `component` are renamed to `renderedComponent` or `mountedComponent` for an improved readability.
Lastly, in the files mentioned above, the `mount` enzyme method is preferred instead of `shallow`.

**How to test**
From the labsystem dir, run `npm test`. Check if all tests pass.

2021-01-04 23:15 UTC, lucianoratamero requested changes

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +  });
while you're checking that the checked icon is there, you're not validating that the input is being marked as checked.
please add this check as well. you may use a similar solution, just checking for `input[checked]` instead.

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
same thing here about the checked value.

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
same here.

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
and here

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(1);
and here

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
:]

2021-01-04 23:15 UTC, lucianoratamero commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(1);
;)

2021-01-05 16:45 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +  });
ok! fixed.

2021-01-05 16:45 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
fixed

2021-01-05 16:47 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
fixed

2021-01-05 16:47 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
fixed

2021-01-05 16:48 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(1);
fixed

2021-01-05 16:48 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(0);
fixed

2021-01-05 16:48 UTC, CavalcanteLucas commented on labsystem/src/Checkbox.test.js
> +    ).toHaveLength(1);
fixed

2021-01-06 16:33 UTC, lucianoratamero approved these changes

2021-01-06 17:37 UTC, merged