DSYS-193: Fix disabled
labcodes/labstorybook pull request #95
Opened 2021-01-12 13:39 UTC by lucianoratamero

**Link to task:** https://labcodes.atlassian.net/browse/DSYS-193
**Staging app:** https://fix-disabled--labstorybook-master.netlify.app/

This PR adds the `ariaDisabled` prop to all buttons and inputs, and add docs on why and how it's used.

2021-01-13 12:43 UTC, CavalcanteLucas requested changes

2021-01-13 12:43 UTC, CavalcanteLucas commented on labsystem/src/Tags/TogglableTag.js
> +        disabled={!ariaDisabled && disabled}
commented above

2021-01-13 12:43 UTC, CavalcanteLucas commented on labsystem/src/Toggle.js
> +          onChange={!ariaDisabled ? this.handleOnChange : () => {}}
```suggestion
          onChange={ariaDisabled ? () => {} : this.handleOnChange}
```

2021-01-13 12:43 UTC, CavalcanteLucas commented on labsystem/src/Toggle.test.js
> +    const shallowedComponent = shallow(
comments above

2021-01-13 12:44 UTC, CavalcanteLucas requested changes
left several comments

2021-01-15 17:45 UTC, lucianoratamero commented on labsystem/src/Button/AbstractButton.test.js
> +    const shallowedComponent = shallow(
hmm, could be. I'll change that.

2021-01-15 17:48 UTC, lucianoratamero commented on labsystem/src/Checkbox.js
> +          onChange={!ariaDisabled ? this.handleOnChange : () => {}}
I prefer leaving it as it is, because the happy path is the one that calls the handleOnChange method, while the ariaDisabled is the excepltion.

2021-01-15 17:51 UTC, lucianoratamero commented on labsystem/src/Button/Button.test.js
> +    const mountedComponent = mount(
I used mount here because the shallow function only renders the component one level deep.
if I use shallow, the "button" html element won't be rendered, since it's two levels deep (Button > AbstractButton > <button>)

2021-01-15 17:52 UTC, lucianoratamero commented on labsystem/src/Checkbox.js
>            {...(value ? { value } : undefined)}
I think it could, but it's not the scope of this task, so I'll leave it as it is for now.

2021-01-15 17:56 UTC, lucianoratamero commented on labsystem/src/Checkbox.js
> +          disabled={(!ariaDisabled && disabled) || undefined}
not in this case, because we **don't** want the input to be disabled **and** ariaDisabled at the same time.
whenever ariaDisabled is true, it overwrites the disabled behavior, rendering the component **without** disabled, but with ariaDisabled instead.
having both would defeat the purpose of having ariaDisabled, since disabled elements are not read by screen readers.

2021-01-15 17:57 UTC, lucianoratamero commented on stories/base/Accessibility.stories.mdx
> +  <p>All of our inputs and buttons have <code>disabled</code> and <code>ariaDisabled</code> props. We made both available because setting them as <code>disabled</code> maked them unreadable by screen
in fact it's `makes` :laughing: 
fixing it.

2021-01-15 17:58 UTC, lucianoratamero commented on stories/base/Accessibility.stories.mdx
> +  <p>Whenever any of our components are set with <code>ariaDisabled</code>, they are functionally identical to their <code>disabled</code> counterparts, with the exception that they will be read by s
:eyes:

2021-01-15 17:58 UTC, lucianoratamero commented on labsystem/src/Tags/AbstractTag.test.js
> +    const mountedComponent = shallow(
ohno

2021-01-19 07:26 UTC, CavalcanteLucas approved these changes
lgtm

2021-01-19 14:05 UTC, merged