DSYS-197: Write dialogs docs
labcodes/labstorybook pull request #96
Opened 2021-01-12 19:35 UTC by CavalcanteLucas

**Link to task**
https://labcodes.atlassian.net/browse/DSYS-197

**How to test**
With the labsystem running, go to the `Dialog` tab and check if everything is according to the documentation.
See https://www.figma.com/file/Wx7jj5klQn3YsRA2XcIV3E/%F0%9F%93%9A-Components?node-id=8904%3A2123 for a detailed reference.

**Description**
This PR translates `Dialog`'s documentation from Figma to Storybook. 
Some adjustments are still required before merging. I leave here some regarding points:
- Are the correct tags used for each section and subsection?
- Is there a CSS for white box with red letters (see subsection "Sizes")?
- Is there a CSS for vertical lines?
- Are the pictures OK?

2021-01-19 20:44 UTC, falconedani requested changes
* Move Standard Dialog, Message Dialog, Modal, and Modeless descriptions to the Usage tab next before the respective example images.
* A doc stylesheet is needed for this page so you can include styles for <caption>.
* The block with white background and pink text style can be created in `.storybook/scss/doc-utils.scss`
* Some image resolutions are not great, I will provide better ones

I've been noticing the use of `<br>` in some of your PRs, please avoid using it unless absolutely necessary.

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +            <p><strong>BUTTON POSITIONING</strong></p>
I'd remove this section. The component already behaves as described so there is no need for such instructions.

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p>Dialogs are components used to display content in a secondary window that appears in a layer above the main window. It should always be triggered by a user's action, not surprising by po
```suggestion
          <p>Dialogs are used to display content in a secondary window that appears in a layer above the main view. It should always be triggered by a user action, not surprising by popping up.</p>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p>It might be used for messages that should be read with attention and, sometimes, blocks the interaction with the rest of the page. In this case, this type of component interrupts user ex
```suggestion
          <p>It might be used for messages that should be read with attention and, sometimes, blocks the interaction with the rest of the page as a <strong>modal</strong>. This type of use interrupts the user experience flow on the underlying page and can be perceived as annoying if used without purpose.</p>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p><strong>Standard Dialog</strong></p>
```suggestion
          <h3>Standard Dialog</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p><strong>Message Dialog</strong></p>
```suggestion
          <h3>Message Dialog</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p><strong>Modal</strong></p>
```suggestion
          <h3>Modal</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p><strong>Modeless</strong></p>
```suggestion
          <h3>Modeless</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +    <p><strong>MOBILE</strong></p>
```suggestion
    <h3>Mobile</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +    <p><em>For mobile, dialogs should be used as modal.</em></p>
```suggestion
    <p><em>Dialogs are always displayed as modal on mobile devices.</em></p>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p>Standard Dialogs should be displayed centered on the viewport, for desktop, and aligned at the bottom, for mobile. Its sizes varies with the context. They can have differents width: <str
```suggestion
          <p>All Dialogs can have two different widths from tablet-up: <strong>default or large</strong>.</p>
          <p>On mobile, Standard Dialogs are always full-width growing vertically from bottom-up, whereas Message Dialogs are centered and takes 90% of the viewport's width and 60% of its height.</p>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p>Standard Dialogs should be displayed centered on the viewport, for desktop, and aligned at the bottom, for mobile. Its sizes varies with the context. They can have differents width: <str
This one is just to sum up and improve comprehension.

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p>Message Dialogs should have the same size and positioning as Standard Dialogs, for Desktop. In mobile screens, this component should have a differente sizing and should be displayered ce
```suggestion
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p>Message Dialogs should have the same size and positioning as Standard Dialogs, for Desktop. In mobile screens, this component should have a differente sizing and should be displayered ce
Included in the previous one.

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +                <p><strong>Default</strong>: 520 px width</p>
```suggestion
                <p><strong>Default</strong>: 520px width</p>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +                <p><strong>Large</strong>: 768 px width</p>
```suggestion
                <p><strong>Large</strong>: 768px width</p>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +          <p><em>The height grows varying to the content, but the mobile scroll full-width has a maxium limit.</em></p>
```suggestion
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +        <p><strong>MODAL</strong></p>
```suggestion
        <h3>Modal</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +        <p><strong>MODELESS</strong></p>
```suggestion
        <h3>Modeless</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +        <p><strong>MOBILE</strong></p>
```suggestion
        <h3>MOBILE</h3>
```

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +        <p><strong>MODAL SCROLL INTERACTION</strong></p>
Not implemented. Remove section.

2021-01-19 20:44 UTC, falconedani commented on stories/Dialog.stories.mdx
> +    <h2>Styles</h2>
Remove section. Not implemented.

2021-01-20 12:29 UTC, CavalcanteLucas commented on stories/Dialog.stories.mdx
> +        </div>
fixed

2021-01-20 12:30 UTC, CavalcanteLucas commented on stories/Dialog.stories.mdx
> +            <p><strong>BUTTON POSITIONING</strong></p>
fixed

2021-01-20 12:32 UTC, CavalcanteLucas commented on stories/Dialog.stories.mdx
> +        <p><strong>MODAL SCROLL INTERACTION</strong></p>
fixed

2021-01-20 12:32 UTC, CavalcanteLucas commented on stories/Dialog.stories.mdx
> +    <h2>Styles</h2>
fixed

2021-01-20 13:25 UTC, CavalcanteLucas commented on stories/Dialog.stories.mdx
> +        <p><strong>WHEN TO USE</strong></p>
fixed

2021-01-20 17:56 UTC, lucianoratamero approved these changes

2021-01-21 12:55 UTC, falconedani approved these changes
LGTM!

2021-01-21 15:38 UTC, merged