Fix tokens
labcodes/labstorybook pull request #99
Opened 2021-01-19 01:10 UTC by debscorreia

**Jira issue:** https://labcodes.atlassian.net/browse/DSYS-166
**Staging app:** https://fix-tokens--labstorybook-master.netlify.app/

2021-01-19 17:49 UTC, falconedani requested changes
Just a few details to decide on.

2021-01-19 17:49 UTC, falconedani commented on stories/Spacing.stories.mdx
>              <tr>
Missing 12

2021-01-19 17:49 UTC, falconedani commented on labsystem/scss/variables/_borders.scss
I got confused why the same pattern used on radius wasn't replicated here. Also, `$border-6` is not used and it doesn't fit the patter, wouldn't it be better to remove? (I believe we used a shadow for the designs that used 6px borders)

2021-01-21 20:12 UTC, lucianoratamero requested changes

2021-01-21 20:12 UTC, lucianoratamero commented on labsystem/scss/variables/_spacing.scss
> +$spacing-12: (12 * $baseline); // 48px
there are a couple of them missing as well: 11 and 14. wast that intentional @debscorreia ?

2021-01-21 20:12 UTC, lucianoratamero commented on labsystem/scss/variables/_spacing.scss
> +$layout-35: (35 * $baseline); // 140px
I think this last one is wrong :thinking:

2021-01-25 19:40 UTC, debscorreia commented on labsystem/scss/variables/_spacing.scss
> +$spacing-12: (12 * $baseline); // 48px
Fixed the order. @lucianoratamero yes, it is intentional. We're not using them, so if at some point someone needs a value in between, it can be easily added without breaking the naming convention.

2021-01-25 19:52 UTC, debscorreia commented on labsystem/scss/variables/_borders.scss
We use a border with 6px. If we want to remove I believe this should be reviewed in another moment from the beginning, including design. But just to remember, it uses 6px because 2px is on the border, so it is at the end 4px. 

Regarding the border, I didn't change it because I don't think it is directly related to the grid and uses small numbers. I changed the naming though to be able to add values in between when needed. We had a naming based on the order. Now I changed it to be related to the actual border size.

2021-01-25 19:53 UTC, debscorreia commented on labsystem/scss/variables/_spacing.scss
> +$layout-35: (35 * $baseline); // 140px
Fixed the last one. But yes, it was intentional. Explaned before.

2021-01-25 21:01 UTC, falconedani approved these changes
LGTM!

2021-01-26 16:37 UTC, lucianoratamero approved these changes

2021-01-26 17:20 UTC, merged